# $Id: Makefile,v 1.5 2008/03/09 15:53:12 yuecelm Exp $ #

# author: Mustafa Yuecel <mustafa.yuecel@alumni.ethz.ch> #

ifndef COMPONENT
#COMPONENT = TestLedAppC
#COMPONENT = TestButtonAppC
COMPONENT = TestUartStreamAppC
endif
TOSMAKE_PATH += ../../support/make
include $(MAKERULES)
#OPTFLAGS = -Os
