#!/bin/sh
# Copyright (c) 2005 Intel Corporation
# All rights reserved.
#
# This file is distributed under the terms in the attached INTEL-LICENSE     
# file. If you do not find these files, copies can be found by writing to
# Intel Research Berkeley, 2150 Shattuck Avenue, Suite 1300, Berkeley, CA, 
# 94704.  Attention:  Intel License Inquiry.


prefix="/usr/local";
exec_prefix="${prefix}";
exec "/Users/boli/Codes/TinyOS-2.x-jhu/opt/nesc/bin/nescc-mig" "-nescc=$exec_prefix/bin/ncc" "$@"
err=$?
echo "Couldn't execute /Users/boli/Codes/TinyOS-2.x-jhu/opt/nesc/bin/nescc-mig" >&2
exit $err
